### ISSUE TITLE
is the mini-remotes supported?

### ISSUE THREAD

**Issue by alfonsolsl** [teharris1/insteon2#15]
i'm trying to use my 8 buttons mini remotes, link the IM as responder (several times), try to override on the config but nothing worked.

The readme is not especific about this devices, only said battery operated devices in general. 

it is possible ?

**Comment by teharris1** [comment]
The mini-remote is supported but with events only. This is the same as the core insteon component and it is described here:
https://www.home-assistant.io/integrations/insteon/#events-and-mini-remotes
