### ISSUE TITLE
service add_default_links fails.

### ISSUE THREAD

**Issue by alfonsolsl** [teharris1/insteon2#18]
The log register exception when the service is triggered.

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.126-v7
python_version | 3.7.7
supervisor | 227
timezone | America/Bogota
version | 0.111.1
virtualenv | false

Component: Insteon2 (Custom)

```
Logger: homeassistant.util.logging
Source: util/logging.py:130
First occurred: 11:32:00 AM (1 occurrences)
Last logged: 11:32:00 AM

Exception in _async_add_default_links when dispatching 'switch.keypadlinc_hab_principal_add_default_links': () Traceback (most recent call last): File "/config/custom_components/insteon2/insteon_entity.py", line 127, in _async_add_default_links await self._insteon_device.async_add_default_links(self.address) TypeError: async_add_default_links() takes 1 positional argument but 2 were given
```

**Comment by alfonsolsl** [comment]
The service tab didn't send any error when triggered.

**Comment by teharris1** [comment]
Thanks. This is a bug in HA and I will get this fixed in the next few days.

**Comment by teharris1** [comment]
I have posted a change to HA that will fix this issue.

**Comment by alfonsolsl** [comment]
i updated to 0.111.4

The description says "entity_id": "all" is possible but i get only error.
