### ISSUE TITLE
Entity State resets at 3am cause lights to turn on

### ISSUE THREAD

**Issue by jbarneson** [teharris1/insteon2#2]
I'm also having difficulty troubleshooting an issue happening overnight. Every night, at exactly 3am, all of my devices seem to reset their state. This causes automations to fire, most of which I've put a condition in to avoid triggering around 3am. When I had insteon coming through MQTT, it was unaffected by whatever was happening within HA, but now that i'm running insteon2 component, i'm getting 4-5 lights turned on at 3am for the past few nights. (including my bedroom :) )... any insight here would be great. I don't think it's your component because i've seen this behavior before and just worked around it. I'm not sure how to workaround this light issue though.....

**Comment by teharris1** [comment]
Can I assume you only have one PLM and that you have checked all your automations to make sure they are not misconfigured? If so, the only thing I can think of is an old technology that existing in early PLMs called a SaLAD script. But I am not sure when they even stopped building that technology into PLMs, plus nobody used it so I would be very surprised if that were it.

**Comment by jbarneson** [comment]
I am on a PLM. But this "3am reset" affects other non-insteon devices.. so it's a broader HA issue. But I posted here because it's startup/reset behavior that could b enice to harden. That being said, last night the devices did not fire..

**Comment by jbarneson** [comment]
This magically just went away. I'm not sure if maybe the restored state for a few of these devices wasn't being respected initially.. But for a few nights I have not noticed any problems.
