### ISSUE TITLE
Possible API call bug?

### ISSUE THREAD

**Issue by glyndon** [teharris1/insteon2#22]
After upgrading from Py3.7.3 to 3.8.6 (and then to 3.9.0), the following appears in the HomeAssistant log during startup. It never appeared before, when running under py3.7.3.

`Logger: homeassistant.config_entries
Source: components/insteon/__init__.py:162
First occurred: 4:58:09 PM (1 occurrences)
Last logged: 4:58:09 PM

Error setting up entry for insteon
Traceback (most recent call last):
  File "/srv/venv3.9.0/lib/python3.9/site-packages/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/srv/venv3.9.0/lib/python3.9/site-packages/homeassistant/components/insteon/__init__.py", line 162, in async_setup_entry
    model=f"{devices.modem.model} (0x{devices.modem.cat:02x}, 0x{devices.modem.subcat:02x})",
  File "/usr/local/lib/python3.9/enum.py", line 663, in __format__
    return cls.__format__(val, format_spec)
ValueError: Unknown format code 'x' for object of type 'str'
`
I'm not sure if this is the module that causes it, or if it's a bug in the newer python library 'enum' file.
HA Core 116.2, RaspberryPi 3b+, latest RaspbianLite, locally-built python 
(locally-built all the pythons I use with HA, since the distro's package is too old)

**Comment by teharris1** [comment]
You should not be using this add-on any longer. The capabilities of this add-on are built into the standard Home Assistant with the built-in `Insteon` integration. Please perform the following steps to migrate:

1. Remove `insteon2` from your `configuration.yaml` file
2. Delete all Home Assistant entities associated with the `insteon2` component using `Configuration -> Entities`
3. Add the Insteon integration using `Configuration -> Integrations` and search for `Insteon`. Follow the prompts as needed.

**Comment by glyndon** [comment]
I posted the report on the wrong place. My bad. I am using the 'stock'
Insteon integration.

--
  Gary Dobbins
