### ISSUE TITLE
Thermostat Current State

### ISSUE THREAD

**Issue by jbarneson** [teharris1/insteon2#3]
I'm missing the "current state" of my thermostat -- ie "is_heating",  "is_cooling", or "off". Different from the mode, the current_state gives me something to key off of when a zone in my house turns on. I use this in my UI to elevate the thermostat to a visible state on my tablets. 

I know the thermostat relays this information. I was using it in insteon_mqtt and it was just stored in an attribute on the climate entity. Understanding this is a feature request -- it would be very helpful.

**Comment by teharris1** [comment]
Can you send me the automation that you use this with? 

Do you need it to be a attribute or can it be an event? Seems like it would be an event you would listen to but I could go either way on that.  Proposal would be for an event `insteon.heating` etc.

**Comment by jbarneson** [comment]
I actually primarily use the state in UI visualizations, so an attribute would work better for my use case, but I like the idea of an event for automations too. I could very easily consume the event in an automation and apply it to an binary_sensor i use to show state history. So either would work well for me and I'd be much appreciative of it getting added 

  - card:
      cards:
        - entity: climate.zone_1
          style: |
            ha-card {
              font-size: 12px;
            }
            **{% if state_attr('climate.zone_1', 'hvac_action') == 'heating' %}**
            @keyframes blink {
              50% {
                background: red;
              }
            }
            ha-card {
              animation: blink 6s linear infinite;
            }
            {% endif %};    
          type: thermostat
        - cards:
            - entities:
                - entity: binary_sensor.zone1_heating
                  name: heat
              type: history-graph
          type: horizontal-stack
        - align_state: center
          color_thresholds:
            - color: '#c0392b'
              value: 80
            - color: '#d35400'
              value: 74
            - color: '#f39c12'
              value: 68
          decimals: 0
          entities:
            - entity: sensor.zone_1_temperature
              index: 0
              show_fill: false
            - color: red
              entity: sensor.zone1_target_temp_high
              index: 1
              show_fill: false
            - color: blue
              entity: sensor.zone1_target_temp_low
              index: 2
              show_fill: false
            - color: red
              entity: sensor.zone1_heating_numeric
              index: 3
              show_line: false
              show_points: false
              y_axis: secondary
            - color: blue
              entity: sensor.zone1_cooling_numeric
              index: 4
              show_line: false
              show_points: false
              y_axis: secondary
          height: 200
          hours_to_show: 24
          icon: 'mdi:temperature-fahrenheit'
          line_color: var(--accent-color)
          line_width: 8
          lower_bound: 60
          points_per_hour: 4
          show:
            labels: true
            legend: false
          type: 'custom:mini-graph-card'
          upper_bound: 80
      type: vertical-stack
    **conditions:
      - entity: binary_sensor.zone1_heating
        state: 'on'**
    type: conditional

**Comment by teharris1** [comment]
OK, I think I did this right. The attribute name is "hvac action", no underscore. This is due to new naming standards that HA is enforcing. Values are "off", "heating", "cooling".  Let me know if it works.

**Comment by jbarneson** [comment]
Updated my insteon2 component, but my thermostats are reporting as "unavailable" now. I let it sit for a cycle or two of the thermostats kicking on, but no updates in HA. 

I think it's related to #4  . Found a startup error: 

`Logger: homeassistant.components.climate
Source: custom_components/insteon2/climate.py:68
Integration: Climate (documentation, issues)
First occurred: 8:02:51 AM (1 occurrences)
Last logged: 8:02:51 AM

Error while setting up insteon2 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 380, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 181, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 490, in min_temp
    DEFAULT_MIN_TEMP, TEMP_CELSIUS, self.temperature_unit
  File "/config/custom_components/insteon2/climate.py", line 68, in temperature_unit
    if self._insteon_device.properties[CELSIUS].value:
KeyError: 'celsius'`

**Comment by teharris1** [comment]
Yeah, I found that too after I sent the post. I updated it to be correct now.

**Comment by jbarneson** [comment]
Updated and looks great -- I'll keep an eye on it's behavior for a few days and report back if anything funky comes up

**Comment by jbarneson** [comment]
current action doesn't seem to be updating... watched it off an on today and all i'm getting is "off":

![image](https://user-images.githubusercontent.com/4008317/79380204-b7a85000-7f25-11ea-85d1-7f63a83be88c.png)

**Comment by teharris1** [comment]
Yup, cuz I never told HA to update the entity state if those status's change in the device. Just pushed a change for this.

**Comment by jbarneson** [comment]
i didn't see any commit come through yesterday? was the update in pyinsteon?

**Comment by teharris1** [comment]
The `climate.py` file was updated yesterday in `insteon2`

**Comment by teharris1** [comment]
@jbarneson  One breaking change I just made for the thermostat is that `hvac action` (no underscore) is back to `hvac_action` (with an underscore). On further review that is a standard climate platform item so I used that rather than my custom `hvac action`.
