### ISSUE TITLE
minor enhancement: "temperature" attribute changed to "target_temperature"

### ISSUE THREAD

**Issue by jbarneson** [teharris1/insteon2#7]
I really like that you have both "temperature" and "target high/low" attributes depending on what mode your in. For better consistency/clarity... is it possible to change "temperature" to "target_temperature". I was confused by the label for a bit.

My suspicion is this is how the climate object works in HA, so you're bound to their configuration... but i thought i'd throw it up here since we talked attributes earlier.

![image](https://user-images.githubusercontent.com/4008317/79570677-85ab0100-807f-11ea-9c86-3cb29634e838.png)

**Comment by teharris1** [comment]
Unfortunately, your suspicion is right. All of those attributes are ones that are defined by HA. I agree with you it would be better to call it `target_temperature`.
